### ISSUE TITLE
打不开诶

### ISSUE THREAD

**Issue by yifanconnected** [LehaoLin/CUHKSZ_Notes_Downloader#1]
![Screen Shot 2020-03-12 at 8.21.05 PM.png](https://i.loli.net/2020/03/12/pkyEHzB4sZIqQLX.png)

系统是10.15.3

**Comment by LehaoLin** [comment]
好的，稍等一下

**Comment by LehaoLin** [comment]
现在重新下载试一试？

**Comment by yifanconnected** [comment]
多次双击和右键Open之后玄学打开了，终端输出正常

On Mar 13, 2020 12:31 AM, Lehao Lin <notifications@github.com> wrote:

现在重新下载试一试？

**Comment by LehaoLin** [comment]
大神你还知道有什么打包的办法吗？

> 2020年3月13日 上午1:45，yifanconnected <notifications@github.com> 写道：
> 
> 
> 多次双击和右键Open之后玄学打开了，终端输出正常 
>
